#!/usr/bin/env perl
# $Id: disp_post,v 1.4 2003/08/05 16:26:37 s42335 Exp $
#
# usage: disp_post post
#    or: disp_post -    (from stdin)
#
# display the content of post (POSTscript) table.
# output format is compatible with make_post.
#
#	2002/2/3, by 1@2ch
#	* public domain *
#

$p=$0; $p=~s:[^/]+$::; push(@INC,$p);
require 'lib_form.pl';
require 'form_post.pl';

disp_form(@ARGV);
