#!/usr/bin/env perl
# $Id: disp_hmtx,v 1.5 2003/09/07 23:26:44 euske Exp $
#
# usage: disp_hmtx hmtx numberOfMetrics numGlyphs
#    or: disp_hmtx -  numberOfMetrics numGlyphs  (from stdin)
#
# display the content of hmtx/vmtx (Horizontal/Vertical MeTriX) table.
#
# NOTE: output format is *NOT* compatible with my make_hmtx...
#
#	2002/2/3, by 1@2ch
#	* public domain *
#

$p=$0; $p=~s:[^/]+$::; push(@INC,$p);
require 'lib_util.pl';

sub usage() {
    print "usage: disp_hmtx hmtx hhea:numberOfHMetrics maxp:numGlyphs\n";
    exit 1;
}

3 <= @ARGV || usage();
($f, $numofHMetrics, $numGlyphs) = @ARGV;
ropen($f);
print "hMetrics:\n";
for(my $i = 0; $i < $numofHMetrics; $i++) {
    my $advanceWidth = ruint16();
    my $leftSideBearing = rsint16();
    print "$i:\t$advanceWidth\t$leftSideBearing\n";
}

print "\nleftSideBearing:\n";
for(my $i = 0; $i < $numGlyphs-$numofHMetrics; $i++) {
    print "$i:\t", rsint16(), "\n";
}
rclose();
