#!/usr/bin/env perl
# $Id: make_OS_s2,v 1.4 2003/08/05 16:26:37 s42335 Exp $
#
# usage: make_OS_s2 OS2.src
#
# build a OS/2 (OS/2 or Windows compatibility) table.
# source format is compatible with disp_OS_s2.
#
#	2002/2/3, by 1@2ch
#	* public domain *
#

$p=$0; $p=~s:[^/]+$::; push(@INC,$p);
require 'lib_form.pl';
require 'form_os2.pl';

make_form(@ARGV);
