#!/usr/bin/env perl
# $Id: make_vhea,v 1.4 2003/08/05 16:26:37 s42335 Exp $
#
# usage: make_vhea vhea.src
#
# build a vhea (Vertical metrics table HEAder) table.
# source format is compatible with disp_vhea.
#
#	2002/2/3, by 1@2ch
#	* public domain *
#

$p=$0; $p=~s:[^/]+$::; push(@INC,$p);
require 'lib_form.pl';
require 'form_vhea.pl';

make_form(@ARGV);
