#!/usr/bin/env perl
# $Id: make_hhea,v 1.4 2003/08/05 16:26:37 s42335 Exp $
#
# usage: make_hhea hhea.src
#
# build a hhea (Horizontal metrics table HEAder) table.
# source format is compatible with disp_hhea.
#
#	2002/2/3, by 1@2ch
#	* public domain *
#

$p=$0; $p=~s:[^/]+$::; push(@INC,$p);
require 'lib_form.pl';
require 'form_hhea.pl';

make_form(@ARGV);
