#!/usr/bin/env perl
# $Id: make_vmtx,v 1.4 2003/08/05 16:26:37 s42335 Exp $
#
# usage: make_vmtx BDF ppem unitem
#
# build a vmtx (Vertical MeTriX) table and dump it into stdout.
#
# NOTE: source format is *NOT* compatible with disp_hmtx.
#
#	2002/2/6, by 1@2ch
#	* public domain *
#

$p=$0; $p=~s:[^/]+$::; push(@INC,$p);
require 'lib_util.pl';

sub usage {
    print "usage: make_vmtx BDF ppem unitem\n";
    exit 1;
}

3 <= @ARGV || usage();
($f, $pixels, $unitem) = @ARGV;

wopen('&STDOUT');
open(IN, $f) || die("open: $f: $!");
while($_ = getline(IN)) {
    if (/^BBX\s*\d+\s*(\d+)\s*\d+/) {
	wuint16(int($unitem * $1 / $pixels));
	wsint16(0);
    }
}
wclose();
